{% set name = "soilgrids" %}
{% set version = "0.1.5" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/gantian127/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: dcdc7661be6e798a67e821790d122ba61b26402a4aa52d0a0d51e7d8f0a61945

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - soilgrids=soilgrids.cli:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}
    - numpy
    - rioxarray
    - xarray
    - requests
    - pyyaml
    - click
    - bmipy
    - netcdf4
    - owslib

test:
  requires:
    - python {{ python_min }}
  imports:
    - soilgrids

about:
  home: https://github.com/gantian127/soilgrids
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: |
    A Python library to fetch the global gridded soil information from SoilGrids system
  description: |
    soilgrids provides a set of functions that allow downloading of the global gridded 
    soil information from SoilGrids, a system for global digital soil mapping to map the 
    spatial distribution of soil properties across the globe. 
    soilgrids also includes a Basic Model Interface (BMI), which converts the SoilGrids 
    dataset into a reusable, plug-and-play data component (pymt_soilgrids) for the PyMT 
    modeling framework developed by Community Surface Dynamics Modeling System (CSDMS).
  doc_url: https://soilgrids.readthedocs.io
  dev_url: https://github.com/gantian127/soilgrids

extra:
  recipe-maintainers:
    - gantian127
